apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-1
  namespace: argocd
spec:
  project: default
  source:
    path: manifests/nginx-1
    repoURL: 'https://github.com/nkirchhoffer/nginx-clebard'
    targetRevision: HEAD
  destination:
    namespace: nginx
    server: 'https://kubernetes.default.svc'
